[package]
name = "schermz"
version = "0.1.0"
authors = ["trassmann"]
license = "ISC"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
indextree = "4.6.0"
clap = { version = "4.3.0", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml"] }
 